Предложение, как можно выравнять ```stack``` внутри ```struct task``` по 16 байт
AntonKozlov/os226-2021 pull request #132
Opened 2021-11-24 15:23 UTC by IAmFunkyFrog

#121 
Предложение, как можно пофиксить баг, который не позволял использовать ```snprintf```

2021-11-24 20:21 UTC, AntonKozlov requested changes

2021-11-24 20:21 UTC, AntonKozlov commented on sched.c
> +} __attribute__((aligned(16)));
Это выглядит хорошо

2021-11-24 20:21 UTC, AntonKozlov commented on sched.c
> +	char stack[8192 + 8]; // +8 добавлено чтобы внутри функции ctx_make(...) файла ctx.c после того, как мы положим entry на вершину стека адрес регистра %rsp был кратен 16 (выровнен по 16 байт)
А это лучше удостоверить при использовании stack, в ctx_make

2021-11-29 11:57 UTC, IAmFunkyFrog commented on sched.c
> +	char stack[8192 + 8]; // +8 добавлено чтобы внутри функции ctx_make(...) файла ctx.c после того, как мы положим entry на вершину стека адрес регистра %rsp был кратен 16 (выровнен по 16 байт)
Изменил, теперь проверка делается в ctx_make(...)

2021-11-29 12:15 UTC, IAmFunkyFrog commented on ctx.c
>          *(unsigned long *)ctx->rsp = (unsigned long) entry;
Этот фрагмент выглядит немного страшно, но суть его в том, чтобы проверить, куда мы передаем управление при ```ctx_switch(...)```. Если мы передаем управление в какую-либо cкомпилированную функцию (в частности, ```tasktramp(...)```, но может быть и другая), то мы знаем, что такая функция начинается с инструкции endbr64 и ожидает, что (%rsp + 8) % 16 == 0:
<pre>
The end of the input argument area shall be aligned on a 16 (32, if __m256 is
passed on stack) byte boundary. In other words, the value (%rsp + 8) is always
a multiple of 16 (32) when control is transferred to the function entry point. The
stack pointer, %rsp, always points to the end of the latest allocated stack frame
</pre>
Цитата из [System V Application Binary Interface AMD64](https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf ).

Если же мы передаем управление в некоторую "сущность", которая не начинается с endbr64 (например, ```exittramp```), то там мы никаких выравниваний не ожидаем

2021-11-30 18:48 UTC, AntonKozlov commented on ctx.c
>          *(unsigned long *)ctx->rsp = (unsigned long) entry;
Хм, я конечно предложил сделать так. Но скомпилированные функции не обязаны начинаться с endbr. С учётом, что пользователь ctx_make возможно хочет иметь контроль, будет ли стек неявно выровнен или стек должен использоваться как-есть, я бы предложил разделить два использования ctx_make. Например, можно добавить в ctx_make параметр, задающий нужно ли внутри выравнивать стек.

2021-12-01 12:48 UTC, IAmFunkyFrog commented on ctx.c
>          *(unsigned long *)ctx->rsp = (unsigned long) entry;
Я может конечно что-то не так понял, но кажется что из-за [Intel CET](https://www.linuxplumbersconf.org/event/2/contributions/147/attachments/72/83/CET-LPC-2018.pdf), если компилировать код актуальным компилятором GCC он будет обязан вставить endbr64 в начале функции.
Но я согласен, что наверно вариант с добавлением параметра более прозрачный

2021-12-07 18:08 UTC, merged

2021-12-07 18:11 UTC, AntonKozlov commented
Да, так намного лучше! В теории, можно было бы подумать о рефакторинге sched_new, чтобы он передавал параметр просто насквозь. Надо было бы развалить sched_new на два операции: инициализация полей task и инициализация ctx. Но это необязательно.